title: "UCSB CS56 pconrad"
github_url: https://github.com/UCSB-CS56-pconrad/UCSB-CS56-pconrad.github.io
github_repo: UCSB-CS56-pconrad.github.io

#kramdown:
#  parse_block_html: true

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/

  textbooks:
    output: true
    permalink: /textbooks/:path/

  chapters:
    output: true
    permalink: /chapters/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: topic
