title: "UCSB CS56 pconrad"
github_url: https://github.com/UCSB-CS56-pconrad/UCSB-CS56-pconrad.github.io
github_repo: UCSB-CS56-pconrad.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048/
hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 


#kramdown:
#  parse_block_html: true

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/

  textbooks:
    output: true
    permalink: /textbooks/:path/

  hfj:
    output: true
    permalink: /hfj/:path/

  hfdp:
    output: true
    permalink: /hfdp/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: topic

  - scope:
      path: ""
      type: hfj
    values:
      layout: chapter

  - scope:
      path: ""
      type: hfdp
    values:
      layout: chapter
